@ES_HOST = http://192.168.11.242:9200

### 
GET {{ES_HOST}}/_cat/_index


### 
PUT {{ES_HOST}}/my_test/_bulk
Content-Type: application/json

{ "index": { "_id": 1 }}
{ "desc":"I am Pantheon" }
{ "index": { "_id": 2 }}
{ "desc":"I am not Pantheon" }
{ "index": { "_id": 3 }}
{ "desc":"I am Leo" }


### 
